In [3]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [5]:
import pandas as pd

In [4]:
lst  = [45,67,5,45,3]
lst

[45, 67, 5, 45, 3]

# **Series**

In [6]:
ser = pd.Series([45, 67, 5, 45, 3])
ser

0    45
1    67
2     5
3    45
4     3
dtype: int64

In [7]:
type(ser)

pandas.core.series.Series

In [9]:
ser = pd.Series([45, 67, 5, 45, 3] , index=['a' , 'b' , 'c' , 'd' , 'e'])
ser

a    45
b    67
c     5
d    45
e     3
dtype: int64

In [10]:
ser = pd.Series([45, 67, 5, 45, 3] , index=['a' , 'b' , 'c' , 'd' , 'e'] , name = 'age')
ser

a    45
b    67
c     5
d    45
e     3
Name: age, dtype: int64

Data frame

In [ ]:
# using list

In [11]:
lst_of_lst = [['apple',8],['mango',9],["banana" , 89]]
lst_of_lst

[['apple', 8], ['mango', 9], ['banana', 89]]

In [12]:
lst_of_lst[1]

['mango', 9]

In [13]:
lst_of_lst[0][1]

8

In [14]:
lst_of_lst = [['apple',8],['mango',9],["banana" , 89]]
df = pd.DataFrame(lst_of_lst)
df

        0   1
0   apple   8
1   mango   9
2  banana  89

In [15]:
lst_of_lst = [['apple',8],['mango',9],["banana" , 89]]
df = pd.DataFrame(lst_of_lst , columns=['Fruits' , 'Quantity'])
df

   Fruits  Quantity
0   apple         8
1   mango         9
2  banana        89

In [16]:
type(df)

pandas.core.frame.DataFrame

In [18]:
lst_of_lst = [['apple',8],['mango',9],["banana" , 89] , ['oranges ',89]]
df = pd.DataFrame(lst_of_lst , columns=['Fruits' , 'Quantity'])
df

     Fruits  Quantity
0     apple         8
1     mango         9
2    banana        89
3  oranges         89

In [19]:
lst_of_lst = [['apple',8 , 'D'],['mango',9 , 'L'],["banana" , 89 , 'D'] , ['oranges ',89 , 'd']]
df = pd.DataFrame(lst_of_lst , columns=['Fruits' , 'Quantity','Like/Dislike'])
df

     Fruits  Quantity Like/Dislike
0     apple         8            D
1     mango         9            L
2    banana        89            D
3  oranges         89            d

In [ ]:
# using Dictionary

In [22]:
d= {

    'Fruits': ['apple','banana','mango','orange'],
    'Quantity':[8,9,89,89]
}
d

{'Fruits': ['apple', 'banana', 'mango', 'orange'], 'Quantity': [8, 9, 89, 89]}

In [24]:
d= {

    'Fruits': ['apple','banana','mango','orange'],
    'Quantity':[8,9,89,89]
}
df = pd.DataFrame(d)
df

   Fruits  Quantity
0   apple         8
1  banana         9
2   mango        89
3  orange        89

In [25]:
df['Fruits']

0     apple
1    banana
2     mango
3    orange
Name: Fruits, dtype: object

In [26]:
df['Quantity']

0     8
1     9
2    89
3    89
Name: Quantity, dtype: int64

In [28]:
df['Like/Dislike'] = ['D' , 'L' , 'D' , 'L']
df

   Fruits  Quantity Like/Dislike
0   apple         8            D
1  banana         9            L
2   mango        89            D
3  orange        89            L

In [ ]:
# Arithmetic Operators

In [35]:
data = pd.DataFrame({'A':[1,23,4,5,6] , 'B' :[45,67,56,45,34] })
data

    A   B
0   1  45
1  23  67
2   4  56
3   5  45
4   6  34

In [32]:
data['A']

0     1
1    23
2     4
3     5
4     6
Name: A, dtype: int64

In [36]:
data['c'] = [56,78,67,90,100]
data

    A   B    c
0   1  45   56
1  23  67   78
2   4  56   67
3   5  45   90
4   6  34  100

In [37]:
data['c']

0     56
1     78
2     67
3     90
4    100
Name: c, dtype: int64

In [38]:
data['D'] = data['A'] * data["B"]
data

    A   B    c     D
0   1  45   56    45
1  23  67   78  1541
2   4  56   67   224
3   5  45   90   225
4   6  34  100   204

In [ ]:
# Insert  And Delate

In [40]:
data

    A   B    c     D
0   1  45   56    45
1  23  67   78  1541
2   4  56   67   224
3   5  45   90   225
4   6  34  100   204

In [41]:
data.insert(1, 'Alphabets',['a' ,'b','c','d','e'])
data

    A Alphabets   B    c     D
0   1         a  45   56    45
1  23         b  67   78  1541
2   4         c  56   67   224
3   5         d  45   90   225
4   6         e  34  100   204

In [42]:
# Delete

del data['D']
data

    A Alphabets   B    c
0   1         a  45   56
1  23         b  67   78
2   4         c  56   67
3   5         d  45   90
4   6         e  34  100

In [43]:
del data['Alphabets']
data

    A   B    c
0   1  45   56
1  23  67   78
2   4  56   67
3   5  45   90
4   6  34  100

In [44]:
d = data.copy()
d

    A   B    c
0   1  45   56
1  23  67   78
2   4  56   67
3   5  45   90
4   6  34  100

In [45]:
del data

In [46]:
data

NameError: name 'data' is not defined

In [47]:
d

    A   B    c
0   1  45   56
1  23  67   78
2   4  56   67
3   5  45   90
4   6  34  100

In [48]:
{
    'A':[1,23,4,5,6] ,
    'B' :[45,67,56,45,34]

}
d1

    A   B
0   1  45
1  23  67
2   4  56
3   5  45
4   6  34

In [ ]:
# load the data

In [ ]:
import Cost_of_Living_Index_by_Country_2024.csv

ModuleNotFoundError: No module named 'Cost_of_Living_Index_by_Country_2024'

In [52]:
df  = pd.read_csv('Cost_of_Living_Index_by_Country_2024.csv' , nrows = 5)

FileNotFoundError: [Errno 2] No such file or directory: 'Cost_of_Living_Index_by_Country_2024.csv'

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [61]:
df  = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Copy of Cost_of_Living_Index_by_Country_2024.csv' , nrows = 10)
df

,Rank,Country,Cost of Living Index,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index
0,1,Switzerland,101.1,46.5,74.9,109.1,97.0,158.7
1,2,Bahamas,85.0,36.7,61.8,81.6,83.3,54.6
2,3,Iceland,83.0,39.2,62.0,88.4,86.8,120.3
3,4,Singapore,76.7,67.2,72.1,74.6,50.4,111.1
4,5,Barbados,76.6,19.0,48.9,80.8,69.4,43.5
5,6,Norway,76.0,26.2,52.1,79.0,73.5,114.7
6,7,Denmark,72.3,26.4,50.2,64.8,81.3,127.2
7,8,Hong Kong (China),70.8,59.4,65.3,84.6,46.2,109.3
8,9,United States,70.4,41.7,56.6,75.0,67.2,142.3
9,10,Australia,70.2,33.4,52.5,77.3,62.5,127.4

In [62]:
df  = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Copy of Cost_of_Living_Index_by_Country_2024.csv' , nrows = 10 ,usecols = ['Country' , 'Groceries Index'])
df

             Country  Groceries Index
0        Switzerland            109.1
1            Bahamas             81.6
2            Iceland             88.4
3          Singapore             74.6
4           Barbados             80.8
5             Norway             79.0
6            Denmark             64.8
7  Hong Kong (China)             84.6
8      United States             75.0
9          Australia             77.3